//! Message and content types carried by a Chat Completions request or response.
//!
//! Mirrors the OpenAI `ChatCompletionRequest*Message` / `ChatCompletionResponseMessage`
//! schemas, plus the `reasoning`/`reasoning_details` extensions that
//! OpenAI-compatible gateways (OpenRouter, DeepSeek, Anthropic, …) return for
//! thinking models.

use serde::{Deserialize, Serialize};

/// The author of a message (`ChatCompletionRole`).
///
/// Unknown values are preserved verbatim in [`Role::Other`] so a proprietary
/// provider role never fails deserialization.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(from = "String", into = "String")]
pub enum Role {
    Developer,
    System,
    User,
    Assistant,
    Tool,
    Function,
    Other(String),
}

impl From<String> for Role {
    fn from(role: String) -> Self {
        match role.as_str() {
            "developer" => Role::Developer,
            "system" => Role::System,
            "user" => Role::User,
            "assistant" => Role::Assistant,
            "tool" => Role::Tool,
            "function" => Role::Function,
            _ => Role::Other(role),
        }
    }
}

impl From<Role> for String {
    fn from(role: Role) -> Self {
        match role {
            Role::Developer => "developer".to_owned(),
            Role::System => "system".to_owned(),
            Role::User => "user".to_owned(),
            Role::Assistant => "assistant".to_owned(),
            Role::Tool => "tool".to_owned(),
            Role::Function => "function".to_owned(),
            Role::Other(other) => other,
        }
    }
}

/// A chat message.
///
/// One type covers every role: which fields are meaningful depends on `role`
/// (e.g. `tool_call_id` for `tool`, `tool_calls` for `assistant`). Optional
/// fields are omitted when serializing, so a minimal `{"role","content"}`
/// message round-trips unchanged.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct Message {
    pub role: Role,

    /// String, or an array of content parts. Required for most roles; `null`
    /// for an assistant message that only carries `tool_calls`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<Content>,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Refusal text produced by the model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refusal: Option<String>,

    /// Tool calls generated by the model (assistant messages).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,

    /// The tool call this message is answering (tool messages).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,

    /// Deprecated; superseded by [`Message::tool_calls`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function_call: Option<FunctionCall>,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub audio: Option<Audio>,

    /// URL citations (e.g. from web search).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<Vec<Annotation>>,

    /// Plaintext reasoning / thinking (OpenRouter normalizes provider output here).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<String>,

    /// Alias for [`Message::reasoning`] returned by DeepSeek and some gateways.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning_content: Option<String>,

    /// Structured reasoning blocks; replay verbatim for multi-turn tool use.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning_details: Option<Vec<ReasoningDetail>>,
}

impl Message {
    /// A plain `system` message.
    ///
    /// The configured system prompt is prepended to each request rather than
    /// kept in a transcript, so this is the only place one is built.
    pub fn system(content: impl Into<String>) -> Self {
        Message {
            role: Role::System,
            content: Some(Content::Text(content.into())),
            name: None,
            refusal: None,
            tool_calls: None,
            tool_call_id: None,
            function_call: None,
            audio: None,
            annotations: None,
            reasoning: None,
            reasoning_content: None,
            reasoning_details: None,
        }
    }
}

/// The `content` of a message: either plain text or an array of typed parts.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(untagged)]
pub enum Content {
    Text(String),
    Parts(Vec<Part>),
}

/// A `ChatCompletionRequestMessageContentPart`.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Part {
    Text { text: String },
    ImageUrl { image_url: ImageUrl },
    InputAudio { input_audio: InputAudio },
    File { file: FileData },
    Refusal { refusal: String },
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct ImageUrl {
    pub url: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct InputAudio {
    pub data: String,
    pub format: String,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct FileData {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_data: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_id: Option<String>,
}

/// A tool call on a message (`ChatCompletionMessageToolCall` /
/// `ChatCompletionMessageCustomToolCall`), discriminated by `type`.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ToolCall {
    Function { id: String, function: FunctionCall },
    Custom { id: String, custom: CustomCall },
}

/// A complete function call (request/response form; arguments are a JSON string).
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct FunctionCall {
    pub name: String,
    pub arguments: String,
}

/// A complete custom-tool call (input is free-form text or grammar output).
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct CustomCall {
    pub name: String,
    pub input: String,
}

/// A streamed tool-call fragment (`ChatCompletionMessageToolCallChunk`).
///
/// Kept as a permissive struct rather than a tagged enum: after the first
/// fragment, providers send `arguments` deltas without repeating `id`/`type`.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct ToolCallChunk {
    #[serde(default)]
    pub index: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<ToolKind>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function: Option<FunctionCallChunk>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub custom: Option<CustomCallChunk>,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolKind {
    Function,
    Custom,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct FunctionCallChunk {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arguments: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct CustomCallChunk {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input: Option<String>,
}

/// Audio response metadata.
///
/// A request echoes only `id`; a response populates the rest.
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
pub struct Audio {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transcript: Option<String>,
}

/// A message annotation (`ChatCompletionResponseMessageAnnotation`).
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Annotation {
    UrlCitation { url_citation: UrlCitation },
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct UrlCitation {
    pub url: String,
    pub title: String,
    pub start_index: u32,
    pub end_index: u32,
}

/// A structured reasoning block (`reasoning_details[]`).
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(tag = "type")]
pub enum ReasoningDetail {
    #[serde(rename = "reasoning.summary")]
    Summary {
        summary: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        format: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        index: Option<u32>,
    },
    #[serde(rename = "reasoning.encrypted")]
    Encrypted {
        data: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        format: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        index: Option<u32>,
    },
    #[serde(rename = "reasoning.text")]
    Text {
        text: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        signature: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        format: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        index: Option<u32>,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A `system` message goes out as the minimal shape every provider accepts:
    /// the role and the text, with nothing else alongside them.
    #[test]
    fn a_system_message_is_just_a_role_and_its_text() {
        let message = Message::system("Be brief.");
        assert_eq!(
            serde_json::to_string(&message).unwrap(),
            r#"{"role":"system","content":"Be brief."}"#
        );
    }
}
